### ISSUE TITLE
Let's add more dynamic Readme 

### ISSUE THREAD

**Issue by kautukkundan** [kautukkundan/Awesome-Profile-README-templates#11]
Readme which can show realtime stats of your contributions/stars/etc

**Comment by anuraghazra** [comment]
Well this works everywhere👌 

![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)

[![ReadMe Card](https://github-readme-stats.anuraghazra1.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats)](https://github.com/anuraghazra/github-readme-stats)

**Comment by ABSphreak** [comment]
Gotta add it to mine!
Looks sick!

One question tho...
I have added my README to short&sweet but I have a GIF inside of it, is it alright?
