### ISSUE TITLE
Reorder templates to show preview without opening files

### ISSUE THREAD

**Issue by Ambro17** [kautukkundan/Awesome-Profile-README-templates#39]
As i explore the repo, i have to individually click each file to see its preview. Perhaps if they were in their own folder named README.md it would be easier to navigate and preview.

**Comment by kautukkundan** [comment]
Hey @Ambro17 
That's a valid point but even after that you'll have to open each folder to read the contents. 
I am thinking of the possibility to have a static site based on these readmes which could be deployed somewhere.

**Comment by Ambro17** [comment]
That's a great alternative. It could even be a github page.
That would mean it would be free and automatically updated on every merge

**Comment by kautukkundan** [comment]
Exploring the possibilities. I am a bit caught up with something else. Unable to update my own profile Readme 😂

**Comment by Ambro17** [comment]
Why was it closed?
