### ISSUE TITLE
Real time data

### ISSUE THREAD

**Issue by ayushkumar-25** [kautukkundan/Awesome-Profile-README-templates#46]
The real-time data should be matched to the original contributor's account.
Example: **Hits** and **Visitors** data should be matched, of contributor's account to this repository. 
If someone is visiting here, this will not be counted to the contributor's account.

How to solve this?
Correct me, if I'm wrong.

**Comment by kautukkundan** [comment]
Hey @ayushkumar-25 I didn't understand that clearly. Can you please elaborate
