### ISSUE TITLE
How could I do a pull request to contrbute?

### ISSUE THREAD

**Issue by jose-renato-m** [kautukkundan/Awesome-Profile-README-templates#6]
Dear sirs,

I've created my own README.md. How is the procedure for me to do a PR for you? I've nerver done, it's the first time, that's why I'm asking for you.

Regards,

José Renato

**Comment by kautukkundan** [comment]
Hi @jose-renato-m 
It's really easy to make a PR
1. go to this repo's main page and click fork 
2. clone that "forked repo" on your computer
3. add the files/make necessary changes 
4. push the changes on your forked repo 
5. then go to your forked repo's main page
7. You'll see a message like "this repo is X commits ahead..... compare and pull request"
8. from there send a PR 

you can read more in this article -
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Do let me know if you have any more questions 😄 happy to help
